#!/bin/sh
###############################################################################
. ${HOME}/.config/SmokeScreen/smokescreen.conf
cache_dir="${HOME}/.cache/SmokeScreen"

# If script is already running; abort.
if pidof -o %PPID -x "$(basename "$0")"; then
    echo "$(date "+%d.%m.%Y %T") INFO: $(basename "$0") already in progress. Aborting."
    exit 3
fi

if [ ! "${1}" = "" ]; then
	${PLEX_MEDIA_SERVER_HOME}/Plex\ Media\ Scanner ${1}
	exit 0
fi

echo "This program passes a single command line argument through to the Plex Media Scanner"
echo "Make sure you wrap it with quotation marks so that it's seen and treated as a single argument"

exit 3
